---
title: "Week1 Quiz"
author: "Sean Clarke"
date: "3 August 2015"
output: html_document
---

# Q1

```{r}
# Consider the data set given below
# x <- c(0.18, -1.54, 0.42, 0.95)
# And weights given by
# w <- c(2, 1, 3, 1)
# Give the value of μ that minimizes the least squares equation ∑ni=1wi(xi−μ)2
# ans - the mean minimises
x <- c(0.18, -1.54, 0.42, 0.95)
w <- c(2, 1, 3, 1)
sum(x*w)/sum(w)
```

# Q2

```{r}
x <- c(0.8, 0.47, 0.51, 0.73, 0.36, 0.58, 0.57, 0.85, 0.44, 0.42)
y <- c(1.39, 0.72, 1.55, 0.48, 1.19, -1.59, 1.23, -0.65, 1.49, 0.05)
yx <-sum(y*x)
xx <- sum (x*x)
beta1 <- yx/xx
beta1
```

# Q3

```{r}
data("mtcars")
y=mtcars$mpg
x=mtcars$wt
lm(y~x)
```


# Q4
```{r}
# beta1<-cor(y,x)* sd(y)/sd(x)
beta1 <- 0.5 * 1/0.5
beta1
```

# Q5
```{r}
# Students were given two hard tests and scores were normalized to have empirical 
# mean 0 and variance 1. The correlation between the scores on the two tests was 0.4. 
# What would be the expected score on Quiz 2 for a student who had a normalized score 
# of 1.5 on Quiz 1?


cor=0.4
beta1 <- cor
score <- beta1 * 1.5
score
```

# Q6
```{r}
# Consider the data given by the following

# x <- c(8.58, 10.46, 9.01, 9.64, 8.86)
# What is the value of the first measurement if x were normalized (to have mean 0 and variance 1)?

x <- c(8.58, 10.46, 9.01, 9.64, 8.86)
xn <- (x - mean(x))/sd(x)
xn
```


# Q7

```{r}
# Consider the following data set (used above as well). What is the intercept 
# for fitting the model with x as the predictor and y as the outcome?

# x <- c(0.8, 0.47, 0.51, 0.73, 0.36, 0.58, 0.57, 0.85, 0.44, 0.42)
# y <- c(1.39, 0.72, 1.55, 0.48, 1.19, -1.59, 1.23, -0.65, 1.49, 0.05)

# reverse usage of y an x :-)
x <- c(0.8, 0.47, 0.51, 0.73, 0.36, 0.58, 0.57, 0.85, 0.44, 0.42)
y <- c(1.39, 0.72, 1.55, 0.48, 1.19, -1.59, 1.23, -0.65, 1.49, 0.05)
beta1<-cor(y,x)* sd(y)/sd(x)
beta0<-mean(y)-beta1*mean(x)
c(beta0, beta1)
```


# Q8
```{r}
# Consider the data given by
# x <- c(0.8, 0.47, 0.51, 0.73, 0.36, 0.58, 0.57, 0.85, 0.44, 0.42)
# What value minimizes the sum of the squared distances between these points and itself?
# tis mu!
mean(x)
```